"""Bearer token authentication for Antidetect HTTP API.

- If ANTIDETECT_API_TOKEN is set (or generated by ``serve --token``) — fail-closed Bearer auth.
- If no token is configured — open access (desktop Qt background API, local zaliver).
"""

from __future__ import annotations

import os
import secrets

from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

ENV_TOKEN = "ANTIDETECT_API_TOKEN"

_bearer = HTTPBearer(auto_error=False)


def get_configured_token() -> str | None:
    t = (os.environ.get(ENV_TOKEN) or "").strip()
    return t or None


def clear_api_token() -> None:
    """Remove token from process env (open access)."""
    os.environ.pop(ENV_TOKEN, None)


def ensure_api_token(*, explicit: str | None = None) -> tuple[str, bool]:
    """
    Resolve API token and set ANTIDETECT_API_TOKEN in the process env.

    Returns (token, generated) where generated=True if the default ``secret`` was applied.
    Priority: explicit argument → existing env → default ``secret``.
    """
    if explicit is not None and str(explicit).strip():
        token = str(explicit).strip()
        os.environ[ENV_TOKEN] = token
        return token, False
    existing = get_configured_token()
    if existing:
        return existing, False
    token = "secret"
    os.environ[ENV_TOKEN] = token
    return token, True


def require_api_token(
    credentials: HTTPAuthorizationCredentials | None = Depends(_bearer),
) -> None:
    expected = get_configured_token()
    if not expected:
        # Desktop / local: no token configured → allow.
        return
    if credentials is None or credentials.scheme.lower() != "bearer":
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing Bearer token",
            headers={"WWW-Authenticate": "Bearer"},
        )
    provided = credentials.credentials or ""
    if not secrets.compare_digest(provided, expected):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid API token",
            headers={"WWW-Authenticate": "Bearer"},
        )
